version: "3.9"

services:
  node:
    container_name: todo-project
    build: .
    ports:
      - 3000:3000
    volumes:
      - ${PWD-.}:/home/node/app
    environment:
      - GIT_TRACE=1
      - GIT_AUTHOR_NAME=$(git config --global --get user.name)
      - GIT_AUTHOR_EMAIL=$(git config --global --get user.email)
    command: yarn dev --host --port=3000
