version: "3.9"

services:
  node:
    image: node:lts
    ports:
      - 3000:3000
    volumes:
      - ${PWD-.}:/home/node/app
    working_dir: /home/node/app
    user: node
    command: yarn dev --host --port=3000
